# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

WORKDIR /app

# Copy the project files
COPY . .

# Upgrade pip and install the project in editable mode
RUN pip install --upgrade pip \
    && pip install -e .

# Expose port if needed (MCP uses stdio, so not typically required)

CMD ["python", "main.py"]
